version: '3'

services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: cisu
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: cisu_db
#      - MYSQL_ALLOW_EMPTY_PASSWORD
#      - MYSQL_RANDOM_ROOT_PASSWORD

    container_name: mysql
    image: mysql:8.1
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql_network

volumes:
  mysql_volume:

networks:
  mysql_network: