spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/store_api?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration:  7200  # 2h  # 900 # 15min
    refreshTokenExpiration: 604800 # 7 days