spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3307/store?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
#    hibernate:
#      ddl-auto: create
    show-sql: true

